# axes to predict for 3d
axes: [ 'xy', 'xz', 'yz' ]

# list of all segmentation labels
labels: [ 1 ]

# parameters for the inference engine
engine: "BCEngine3d"
engine_params:
  median_kernel_size: 3

watershed_params:
  thres1: 0.3
  thres2: 0.2
  thres3: 0.1
  seed_thres: 500
  min_size: 500
  label_divisor: 10000
  use_mask_wts: True

